language: node_js
node_js:
  - "5.10.1"
sudo: false
branches:
  only:
    - master
    - typescript
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
